#!/bin/sh

### Config ###
## Workspaces
bspc monitor -d one two three four 

## Mod Key
bspc config pointer_modifier mod1

## Pudding
bspc config right_padding 20
bspc config left_padding 20
bspc config bottom_padding 20
bspc config top_padding 80
bspc config windows_gap 20

## Borders
bspc config border_width 10
bg=$(xrdb -query | awk '/\*.foreground/ {print $2}')
bspc config normal_border_color "$bg"
bspc config focused_border_color "$bg"
bspc config presel_feedback_color "$bg"
pkill 2bsp ; 2bsp &

## Focusing
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

## Rules
bspc rule -a URxvt state=floating
